package com.StudyCreated;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.Select;

public class StudyCreated 
{
    public static void main(String[] args) throws InterruptedException 
	{
	WebDriver driver=new FirefoxDriver();
	driver.get("http://accutest.aetiol-eclinical.com/");
	driver.manage().window().maximize();
	driver.findElement(By.xpath(".//*[@id='UserName']")).sendKeys("deepak");
	driver.findElement(By.xpath(".//*[@id='Password']")).sendKeys("Saini@123");
	driver.findElement(By.xpath(".//*[@id='btnSubmit']")).click();
	driver.findElement(By.xpath(".//*[@id='IdUs']")).click();
	driver.findElement(By.xpath(".//*[@id='IdDF']")).click();
	Thread.sleep(1000);
	driver.findElement(By.xpath(".//*[@id='btnAddComGroup']")).click();
	Thread.sleep(1000);
	driver.findElement(By.xpath(".//*[@id='ComGroup']")).sendKeys("heart");
	Thread.sleep(1000);
	driver.findElement(By.xpath(".//*[@id='body']/div[1]/div/div/fieldset/table/tbody/tr[2]/td/table/tbody/tr/td[2]/button[1]")).click();
	Alert a0=driver.switchTo().alert();
	a0.accept();
	Thread.sleep(2000);
	driver.findElement(By.xpath(".//*[@id='body']/div[1]/div/div/fieldset/table/tbody/tr[2]/td/table/tbody/tr/td[2]/button[2]")).click();
	Thread.sleep(1000);
	driver.findElement(By.xpath(".//*[@id='IdDU']")).click();
	Thread.sleep(2000);
	driver.findElement(By.xpath(".//*[@id='tblgridpaging']/tbody/tr/td/table/tbody/tr/td[2]/a[2]")).click();
	driver.findElement(By.xpath(".//*[@id='txtName']")).sendKeys("Jony Jackson");
	driver.findElement(By.xpath(".//*[@id='txtAddress']")).sendKeys("America");
	driver.findElement(By.xpath(".//*[@id='txtEmailID']")).sendKeys("Jony@yopmail.com");
	WebElement web=driver.findElement(By.xpath(".//*[@id='txtRole']"));
	Select s0=new Select(web);
	//s0.selectByVisibleText("DM");
	//s0.selectByVisibleText("Monitor");
	s0.selectByVisibleText("Investigator");
	driver.findElement(By.xpath(".//*[@id='imgUseradd']")).click();
	Thread.sleep(2000);
	Alert a00=driver.switchTo().alert();
	a00.accept();
	Thread.sleep(2000);
	driver.findElement(By.xpath(".//*[@id='IdStudyConfiguration']/span[2]")).click();
	driver.findElement(By.xpath(".//*[@id='Idcs']")).click();
	Thread.sleep(1000);
	driver.findElement(By.xpath(".//*[@id='StudyName']")).sendKeys("Dengue");
	WebElement w=driver.findElement(By.xpath(".//*[@id='PrincipalInvestigator']"));
	Select s=new Select(w);
	s.selectByVisibleText("Jony Jackson");
	driver.findElement(By.xpath(".//*[@id='StudySponser']")).sendKeys("M.K. Shah");
	WebElement w1=driver.findElement(By.xpath(".//*[@id='StudyPhase']"));
	Select s1=new Select(w1);
	s1.selectByVisibleText("I");
	driver.findElement(By.xpath(".//*[@id='Collaborators']")).sendKeys("Jackson");
	driver.findElement(By.xpath(".//*[@id='NoofSites']")).sendKeys("100");
	WebElement w2=driver.findElement(By.xpath(".//*[@id='TimeZone']"));
	Select s2=new Select(w2);
	s2.selectByVisibleText("(UTC-05:00) Indiana (East)");
	driver.findElement(By.xpath(".//*[@id='UniqueProtocolId']")).sendKeys("Dengue111");
	driver.findElement(By.xpath(".//*[@id='StudySummary']")).sendKeys("Dengue fever is a mosquito-borne tropical disease caused by the dengue virus. Symptoms typically begin three to fourteen days after infection.");
    driver.findElement(By.xpath(".//*[@id='createstudyfrm']/div/fieldset/table/tbody/tr[1]/td[2]/table/tbody/tr[4]/td[2]/img")).click();
    Thread.sleep(2000);
    driver.findElement(By.xpath(".//*[@id='ui-datepicker-div']/table/tbody/tr[5]/td[7]/a[@href='#']")).click();
    Thread.sleep(2000);
    driver.findElement(By.xpath(".//*[@id='createstudyfrm']/div/fieldset/table/tbody/tr[1]/td[2]/table/tbody/tr[5]/td[2]/img")).click();
    Thread.sleep(2000);
    driver.findElement(By.xpath(".//*[@id='ui-datepicker-div']/table/tbody/tr[5]/td[7]/a")).click();
    Thread.sleep(2000);
    driver.findElement(By.xpath(".//*[@id='NoofSubjects']")).sendKeys("200");
    WebElement w3=driver.findElement(By.xpath(".//*[@id='SubjectIdentifier']"));
    Select s3=new Select(w3);
    s3.selectByVisibleText("Automatic");
    driver.findElement(By.xpath(".//*[@id='createstudyfrm']/div/fieldset/table/tbody/tr[2]/td/div/button[1]")).click();
    Alert a=driver.switchTo().alert();
    a.accept();
    Thread.sleep(2000);
    driver.findElement(By.xpath(".//*[@id='Idsl']")).click();
    Thread.sleep(2000);
    driver.findElement(By.xpath("//a[contains(text(),'Dengue')]")).click();
	Thread.sleep(2000);
    driver.findElement(By.xpath(".//*[@id='btnEdit']")).click();
	Thread.sleep(1000);
    driver.findElement(By.xpath(".//*[@id='btnSave']")).click();
    Thread.sleep(1000);
    driver.findElement(By.xpath(".//*[@id='btnSaveReason']")).click();
    Alert a1=driver.switchTo().alert();
    a1.accept();
    //JavascriptExecutor js = (JavascriptExecutor)driver;
    //js.executeAsyncScript("window.scrollBy(0,-300)","");
    Thread.sleep(2000);
    WebElement w4=driver.findElement(By.xpath(".//*[@id='stdname']"));
    Select s4=new Select(w4);
    s4.selectByVisibleText("Dengue");
    Alert a2=driver.switchTo().alert();
    a2.accept();
    driver.navigate().refresh();
    Alert a3=driver.switchTo().alert();
    a3.accept();
    Thread.sleep(2000);
    //Alert a33=driver.switchTo().alert();
    //a33.accept();
    //Thread.sleep(2000);
    
    driver.findElement(By.xpath(".//*[@id='idcsite']")).click();
    driver.findElement(By.xpath(".//*[@id='idDisabled']")).click();
    driver.findElement(By.xpath(".//*[@id='txtSiteName']")).sendKeys("Ganganagar");
    WebElement w5=driver.findElement(By.xpath(".//*[@id='txtInvestigator']"));
    Select s5=new Select(w5);
    s5.selectByVisibleText("Jony Jackson");
    driver.findElement(By.xpath(".//*[@id='txtAddress']")).sendKeys("Gujrat");
    driver.findElement(By.xpath(".//*[@id='txtCountry']")).sendKeys("India");
    driver.findElement(By.xpath(".//*[@id='txtEnrollmentTarget']")).sendKeys("100");
    driver.findElement(By.xpath(".//*[@id='txtEnrollmentLimit']")).sendKeys("200");
    driver.findElement(By.xpath(".//*[@id='imgUseradd']")).click();
    Alert a4=driver.switchTo().alert();
    a4.accept();
    Thread.sleep(3000);
    
    driver.findElement(By.xpath(".//*[@id='idcAU']")).click();
    driver.findElement(By.xpath(".//*[@id='idDisabled']")).click();
    WebElement w6=driver.findElement(By.xpath(".//*[@id='GRole']"));
    Select s6=new Select(w6);
    s6.selectByVisibleText("Investigator");
    WebElement w7=driver.findElement(By.xpath(".//*[@id='GSUser']"));
    Select s7=new Select(w7);
    s7.selectByVisibleText("Jony Jackson");
    driver.findElement(By.xpath(".//*[@id='btnAddAssignSites']")).click();
    Thread.sleep(1000);
    driver.findElement(By.xpath(".//*[@id='SiteId0']")).click();
    Thread.sleep(1000);
    driver.findElement(By.xpath(".//*[@id='btnSave']")).click();
    Thread.sleep(1000);
    driver.findElement(By.xpath(".//*[@id='imgUseradd']")).click();
    Thread.sleep(3000);
    Alert a5=driver.switchTo().alert();
    a5.accept();
    Thread.sleep(2000);
    
    driver.findElement(By.xpath(".//*[@id='idcCG']")).click();
    Thread.sleep(1000);
    driver.findElement(By.xpath(".//*[@id='btnGroup']")).click();
    driver.findElement(By.xpath(".//*[@id='txtGroupName']")).sendKeys("Region");
    driver.findElement(By.xpath(".//*[@id='txtEnrollmentTarget']")).sendKeys("100");
    driver.findElement(By.xpath(".//*[@id='txtEnrollmentlimit']")).sendKeys("200");
    driver.findElement(By.xpath(".//*[@id='imggroupadd']")).click();
    Thread.sleep(1000);
    Alert a6=driver.switchTo().alert();
    a6.accept();
    Thread.sleep(2000);
    
    driver.findElement(By.xpath(".//*[@id='idcCV']")).click();
    Thread.sleep(2000);
    driver.findElement(By.xpath(".//*[@id='tblVisit']/tbody/tr[2]/td/table/tbody/tr/td[2]/span/span[1]")).click();
    Thread.sleep(2000);
    driver.findElement(By.xpath(".//*[@id='btnMultipleVisit']")).click();
    Thread.sleep(2000);
    driver.findElement(By.xpath(".//*[@id='txtVisitName']")).sendKeys("base,week");
    Thread.sleep(2000);
    driver.findElement(By.xpath(".//*[@id='imgVisitadd']")).click();
    Thread.sleep(2000);
   // Alert a7=driver.switchTo().alert();
  //  a7.accept();
    //Thread.sleep(2000);
    
	}

}
